### ISSUE TITLE
Graphical issue

### ISSUE THREAD

**Issue by escalade** [libretro/libretro-fsuae#6]
In BattleSquadron the ship renders at the bottom, so whenever it flies over an object it will become "invisible". Not sure if it affects other games, but I would assume so.

Also I'd like to say thanks for this, been waiting a long time for an FS-UAE libretro core. Have you notified Frode about your progress? I asked him if he was considering libretro a long time ago but at the time he wasn't interested.

**Comment by escalade** [comment]
Tested on both x86_64 with Intel HD graphics and on Raspberry Pi 3.

**Comment by repojohnray** [comment]
A new option is available to select the graphic size, and crop the output. e.g.: zoom = 688x464/8/56/680/404 (README.md) I hope it will help.

**Comment by escalade** [comment]
This issue is not related to zooming or cropping. As mentioned in the description, the sprites are messed up appearing at the bottom. So if your ship flies over a cloud, it will be under it and invisible. Please re-open, as it's not fixed.

**Comment by repojohnray** [comment]
Is this specific to libretro-fsuae or the regular FS-UAE is affected too?

**Comment by escalade** [comment]
Standalone FS-UAE is not affected. I seem to recall the PUAE libretro core having the same issue though, I'll confirm that tonight.

**Comment by repojohnray** [comment]
The behavior is the same on the regular FS-UAE. A bug likely located in the emulator core.

**Comment by escalade** [comment]
Sigh... As mentioned, it is NOT the same in regular FS-UAE. Confirmed NOT present in latest FS-UAE git and confirmed PRESENT in latest fsuae-libretro git.

I've also checked the latest puae_libretro core and it's not present there.
