### ISSUE TITLE
Build failure with autotools.

### ISSUE THREAD

**Issue by orbea** [libretro/libretro-fsuae#8]
OS: `Slackwar64-current`
`gcc-5.4.0`

So I decided to try the autotools, it does not build either...
```
sources/src/drawing.c:1316:30: fatal error: ../gen/linetoscr.c: No such file or directory
compilation terminated.
Makefile:143: recipe for target 'sources/src/drawing.o' failed
make: *** [sources/src/drawing.o] Error 1
make: *** Waiting for unfinished jobs....
```
Build log: http://pastebin.com/6S2xnJeq

**Comment by orbea** [comment]
This may be related. http://eab.abime.net/showthread.php?t=51887

**Comment by repojohnray** [comment]
The following command generates 'linetoscr.c' and some other files:
make gen

--
README.md contains the full sequence.

**Comment by orbea** [comment]
Thanks! `make gen` is what I was missing, in retrospect I should of read the README.md better... It builds here now so I will close this.
