### ISSUE TITLE
Making a lakka core for arm

### ISSUE THREAD

**Issue by Ntemis** [libretro/libretro-fsuae#9]
Hello,
 i need some help adding support in lakka for fsuae
this is the package i made reading the readme of the repo.
http://dpaste.com/14PNPDG
Any help appreciated
Regards

**Comment by repojohnray** [comment]
Do you generate the 'fsuae_libretro.so' library without any compilation issue using the definition above?

Adding the file: 'fs-uae.dat' is better; It contains, the FDD sound, and the data required to use the emulator beyond the A1200 mode. The path must be relative to the 'retroarch' executable (README.md contains the paths list).

'fsuae_libretro.so' and fs-uae.dat' are the only two files required by the emulator.

**Comment by sergiobenrocha2** [comment]
```
base/fs-uae.dat, base/../share/fs-uae/fs-uae.dat or base/../../Data/fs-uae.dat
```

Shouldn't it be located at the System/BIOS dir? RETRO_ENVIRONMENT_GET_SYSTEM_DIRECTORY

**Comment by repojohnray** [comment]
The code still uses the legacy fsuae directory scheme. A change is likely better.

**Comment by repojohnray** [comment]
RETRO_ENVIRONMENT_GET_LIBRETRO_PATH added to the search path.

RETRO_ENVIRONMENT_GET_SYSTEM_DIRECTORY can be added too.
